# Generated by Django 5.0.6 on 2024-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0010_privatekeypermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='digital_signature',
            field=models.TextField(blank=True, editable=False, help_text='The digital signature of the feedback.', null=True, verbose_name='Digital Signature'),
        ),
    ]
